### ISSUE TITLE
please add some documentation to understand to the implementation

### ISSUE THREAD

**Issue by sravanth-space** [philippphb/documentary.#1]

**Comment by philippphb** [comment]
I added comments in the source code of all files. Please have a look! Let me know if you need any specific information.

**Comment by sravanth-space** [comment]
how to run the app locally

**Comment by philippphb** [comment]
Ok, just clone the repository and open the file src/main/webapp/index.html in a web browser locall.
Note that if you are using Metamask, you should open the file directly from the file system, because meta mask does not support that. Instead, you need to serve the file using a local Webserver. You can use XAMPP for example, it's easy to use. Clone this repository under the XAMPP/htdocs folder then.

**Comment by sravanth-space** [comment]
yes it works with vscode live server.
